  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.2'
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${DEFAULT_PASSWORD}
    ports:
      - 8080:8080
    command: start-dev
    networks:
      - gitlab
    hostname: '${HOST_IP}'