services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    restart: "always"
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
