FROM hashicorp/vault:latest

ADD /config /vault/config
ADD entrypoint.sh /
RUN chmod +x entrypoint.sh
RUN chown -R vault:vault /vault
# # CMD ./entrypoint.sh

# ENTRYPOINT [ "./entrypoint.sh" ]
# CMD vault server -config=/vault/config/vault.json

ENTRYPOINT [ "docker-entrypoint.sh" ]
CMD ["server"]