services:
  gitlab-runner-shell:
    image: armyguy255a/gitlab-runner-shell:latest
    restart: "no"
    environment:
      - GIT_SSL_NO_VERIFY=1
      - GITLAB_URL=https://$HOST_IP:8443
      - GITLAB_REGISTRATION_TOKEN=$REGISTRATION_TOKEN
      - TAG_LIST=shell,vsphere,atmos,pwsh,ubuntu,bash
      - SSH_PORT="8443"
    volumes:
      - ./volumes/config:/etc/gitlab-runner
      - ./volumes/home:/home/gitlab-runner
    command: run